[package]
name = "mpt"
version = "0.1.0"
authors = ["Pius Meinert <yrr+work@pm.me>"]
edition = "2018"

[dependencies]
nalgebra = "0.18"
# TODO wait for log_domain sum trait push
# log_domain = "0.4.0"
log_domain = { path = "../tests/rust-log-domain/" }
priority-queue = "0.6.0"
num-traits = "0.2.8"
