[package]
name = "mpt"
version = "0.1.0"
authors = ["Pius Meinert <yrr+work@pm.me>"]
edition = "2018"

[dependencies]
log_domain = { git = "https://github.com/tud-fop/rust-log-domain.git" }
nalgebra = "0.18"
nom = "4.2.3"
num-traits = "0.2.8"
priority-queue = "0.6.0"
